from datetime import datetime
import helics as h
from dots_infrastructure.DataClasses import TimeStepInformation, EsdlId, HelicsCalculationInformation, PublicationDescription, SubscriptionDescription
from dots_infrastructure.HelicsFederateHelpers import HelicsSimulationExecutor
from esdl import EnergySystem

# This file is generated, DO NOT edit this file!

class WeatherServiceBase(HelicsSimulationExecutor):

    def __init__(self):
        super().__init__()

        
        # Calculation: weather_prediction
        weather_prediction_inputs = [
        
        ]
        weather_prediction_outputs = [
        
            PublicationDescription(global_flag=True, 
                                    esdl_type="EnvironmentalProfiles",
                                    output_name="solar_irradiance",
                                    output_unit="Wm2", 
                                    data_type="VECTOR"),
            PublicationDescription(global_flag=True, 
                                    esdl_type="EnvironmentalProfiles",
                                    output_name="air_temperature",
                                    output_unit="K", 
                                    data_type="VECTOR"),
            PublicationDescription(global_flag=True, 
                                    esdl_type="EnvironmentalProfiles",
                                    output_name="soil_temperature",
                                    output_unit="K", 
                                    data_type="VECTOR"),
        ]
        weather_prediction_information = HelicsCalculationInformation(
            time_period_in_seconds=900,
            offset=0, 
            uninterruptible=False, 
            wait_for_current_time_update=False, 
            terminate_on_error=True, 
            calculation_name="weather_prediction", 
            inputs=weather_prediction_inputs, 
            outputs=weather_prediction_outputs, 
            calculation_function=self.weather_prediction
        )
        self.add_calculation(weather_prediction_information)
        # Calculation: current_current_weather_data
        current_current_weather_data_inputs = [
        
        ]
        current_current_weather_data_outputs = [
        
            PublicationDescription(global_flag=True, 
                                    esdl_type="EnvironmentalProfiles",
                                    output_name="solar_irradiance",
                                    output_unit="Wm2", 
                                    data_type="DOUBLE"),
            PublicationDescription(global_flag=True, 
                                    esdl_type="EnvironmentalProfiles",
                                    output_name="air_temperature",
                                    output_unit="K", 
                                    data_type="DOUBLE"),
            PublicationDescription(global_flag=True, 
                                    esdl_type="EnvironmentalProfiles",
                                    output_name="soil_temperature",
                                    output_unit="K", 
                                    data_type="DOUBLE"),
        ]
        current_current_weather_data_information = HelicsCalculationInformation(
            time_period_in_seconds=900,
            offset=0, 
            uninterruptible=False, 
            wait_for_current_time_update=False, 
            terminate_on_error=True, 
            calculation_name="current_current_weather_data", 
            inputs=current_current_weather_data_inputs, 
            outputs=current_current_weather_data_outputs, 
            calculation_function=self.current_current_weather_data
        )
        self.add_calculation(current_current_weather_data_information)

    
    def weather_prediction(self, param_dict : dict, simulation_time : datetime, time_step_number : TimeStepInformation, esdl_id : EsdlId, energy_system : EnergySystem):
        pass
    
    def current_current_weather_data(self, param_dict : dict, simulation_time : datetime, time_step_number : TimeStepInformation, esdl_id : EsdlId, energy_system : EnergySystem):
        pass
    